# Generated by Django 4.1 on 2022-09-03 11:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id_класса')),
                ('name_class', models.CharField(max_length=20, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Articles2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_teacher', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id_учителя')),
                ('full_name', models.CharField(max_length=20, verbose_name='ФИО')),
                ('Qualification', models.CharField(max_length=20, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Articles3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subject', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='id предмета')),
                ('name_subject', models.CharField(max_length=20, verbose_name='Название предмета')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Articles4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles')),
                ('id_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles3')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.articles2')),
            ],
            options={
                'verbose_name': 'Учебная деятельность',
                'verbose_name_plural': 'Учебная деятельность',
            },
        ),
    ]
